#!/bin/bash

# Expense Tracker - Payment Gateway Setup Guide
# This script helps you set up Stripe for the Expense Tracker application

echo "==================================="
echo "Stripe Payment Gateway Setup"
echo "==================================="
echo ""

echo "IMPORTANT: Before running the application, you need to:"
echo ""
echo "1. CREATE STRIPE ACCOUNT"
echo "   - Go to https://dashboard.stripe.com/register"
echo "   - Complete registration and verification"
echo ""

echo "2. GET STRIPE API KEYS"
echo "   - Go to https://dashboard.stripe.com/apikeys"
echo "   - Copy your STRIPE_SECRET_KEY (starts with sk_test_)"
echo "   - Copy your STRIPE_PUBLISHABLE_KEY (starts with pk_test_)"
echo ""

echo "3. GET WEBHOOK SECRET (Optional but recommended)"
echo "   - Go to https://dashboard.stripe.com/webhooks"
echo "   - Create endpoint for http://your-backend-url/api/payments/webhook"
echo "   - Copy the webhook secret (starts with whsec_)"
echo ""

echo "4. CONFIGURE ENVIRONMENT VARIABLES"
echo ""
echo "   Backend (.env):"
echo "   ==============="
echo "   STRIPE_SECRET_KEY=sk_test_your_key"
echo "   STRIPE_WEBHOOK_SECRET=whsec_your_secret"
echo ""

echo "   Frontend (.env.local or .env):"
echo "   ==============================="
echo "   VITE_STRIPE_PUBLIC_KEY=pk_test_your_key"
echo ""

echo "5. INSTALL DEPENDENCIES"
echo "   Backend:"
echo "   pip install -r requirements.txt"
echo ""
echo "   Frontend:"
echo "   npm install"
echo ""

echo "6. SETUP DATABASE"
echo "   - Configure DATABASE_URL in .env"
echo "   - Tables will auto-create on first run"
echo ""

echo "7. RUN THE APPLICATION"
echo "   Backend:"
echo "   uvicorn app.main:app --reload"
echo ""
echo "   Frontend:"
echo "   npm run dev"
echo ""

echo "==================================="
echo "PAYMENT FEATURES"
echo "==================================="
echo ""
echo "✅ Debt Payment:"
echo "   - Pay bank EMI/loan with Stripe"
echo "   - Reduces remaining_amount automatically"
echo "   - Marks debt as 'paid' when zero balance"
echo ""
echo "✅ Split Expense Payment:"
echo "   - Pay exact split amount to the creator"
echo "   - Prevents double payment (idempotency)"
echo "   - Records payment in transaction history"
echo ""
echo "✅ Payment Methods:"
echo "   - Card (Debit/Credit)"
echo "   - UPI (India specific)"
echo "   - Currency: INR (Indian Rupees)"
echo ""
echo "✅ Security:"
echo "   - Stripe Webhook integration for confirmation"
echo "   - Idempotency keys to prevent duplicate charges"
echo "   - Environment variables for sensitive data"
echo "   - Secure CORS configuration"
echo ""

echo "==================================="
echo "TESTING"
echo "==================================="
echo ""
echo "Use Stripe Test Cards:"
echo "- Success: 4242 4242 4242 4242"
echo "- Decline: 4000 0000 0000 0002"
echo "- Expiry: Any future date (e.g., 12/25)"
echo "- CVC: Any 3 digits"
echo ""

echo "Test UPI (uses test mode):"
echo "- Just enter any valid UPI ID format: name@bank"
echo ""

echo "==================================="
echo "DOCUMENTATION"
echo "==================================="
echo ""
echo "API Endpoints:"
echo "- POST /api/payments/create-intent"
echo "- POST /api/payments/confirm-payment"
echo "- POST /api/payments/webhook"
echo "- GET /api/payments/history"
echo "- GET /api/payments/{transaction_id}"
echo ""

echo "Components:"
echo "- PaymentForm.jsx: Interactive payment UI"
echo "- PaymentModal.jsx: Modal wrapper"
echo "- TransactionHistory.jsx: View all transactions"
echo ""

echo "==================================="
echo "Setup Complete!"
echo "==================================="
